site_name: Портфолио
site_url: https://alextrubkina.github.io
site_author: Alexandra Trubkina
nav:
    - Главная страница: index.md
    - Модуль "Историко-философский": history.md
    - Модуль "Коммуникативный": communication.md
    - Модуль "Здоровьесберегающий": healthcare.md
    - Модуль "Естественно-математический": naturemath.md
    - Модуль "Организация ЭВМ": orgevm.md
    - Модуль "Системное и прикладное программное обеспечение": systempricpo.md
    - Модуль "Дискретные структуры": diststruct.md
    - Модуль "Технологии и методы вычислений": techmethvch.md
    - Модуль "Информационные технологии в математике и физике": itmathphis.md
    - Модуль"Проектирование и разработка веб-решений": web.md
    - Модуль "Информационные технологии в управлении в IT-компании": itcomp.md
    - Модуль "Информационные технологии": it.md
    - Модуль "Экономико-правовой": economic.md
    - Модуль "Информационные ресурсы и средства профессиональной деятельности инженера": itpoing.md
    - Модуль "Информационные технологии и системы": its.md
    - Модуль "Учебно-исследовательский": uchisl.md
    - Физическая культура и спорт (элективная дисциплина): sport.md
    - Модуль "Основы профессионального общения на иностранном языке": inlangosn.md
    - Модуль "Теоретические и практичеcкие аспекты переводоведения": perevod.md
    - Модуль "Особенности профеcсиональной иноязычной коммуникации": incomm.md
    - Автор: about.md
theme:
    name: readthedocs
